#Docker compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'

#Define Services
services: 
  #App backend Service
  app-businesslogic: 
    build: 
      context: cyri-blms
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks: 
      - fervor
  app-gameservice:
    build: 
      context: cyri-gs
      dockerfile: Dockerfile
    ports: 
      - "8081:8080"
    restart: always
    networks: 
      - fervor
  app-phoneservice:
    build: 
      context: cyri-ps
      dockerfile: Dockerfile
    ports: 
      - "8082:8080"
    restart: always
    networks: 
      - fervor
  #frontend service
  app-reactfrontend:
    build:
      context: cyri-ui
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - app-businesslogic
      - app-gameservice
      - app-phoneservice
    networks:
      - fervor 
      
#volumes
#volumes:
  #db-data: 

networks:
  fervor: 