#Docker compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.7'

#Define Services
services: 
  #App backend Service
  app-businesslogic: 
    build: 
      context: cyri-blms
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks: 
      - fervor
  app-gameservice:
    build: 
      context: cyri-gs
      dockerfile: Dockerfile
    ports: 
      - "8081:8080"
    restart: always
    networks: 
      - fervor
      
#volumes
#volumes:
  #db-data: 

networks:
  fervor: 